name: bpmf_py
description: A bopomofo and pinyin processing library. It provides parsing of both the standard mandarin phonetic notations, and conversion between them.
version: 0.2.0
repository: https://github.com/blankego/bpmf_py_dart

environment:
  sdk: ^3.3.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
