import 'bpmf_codes.dart';

const untonedFinalsToMedRime = [
  ('a', (0, $a)),
  ('o', (0, $o)),
  ('e', (0, $e)),
  ('ê', (0, $eh)),
  ('eh', (0, $eh)),
  ('ai', (0, $ai)),
  ('ei', (0, $ei)),
  ('er', (0, $er)),
  ('ao', (0, $ao)),
  ('ou', (0, $ou)),
  ('an', (0, $an)),
  ('en', (0, $en)),
  ('ang', (0, $ang)),
  ('eng', (0, $eng)),
  ('i', ($i, 0)),
  ('ia', ($i, $a)),
  ('io', ($i, $o)),
  ('ie', ($i, $eh)),
  ('iai', ($i, $ai)),
  ('iao', ($i, $ao)),
  ('iu', ($i, $ou)),
  ('iou', ($i, $ou)),
  ('ian', ($i, $an)),
  ('in', ($i, $en)),
  ('iang', ($i, $ang)),
  ('ing', ($i, $eng)),
  ('u', ($u, 0)),
  ('ua', ($u, $a)),
  ('uo', ($u, $o)),
  // ('ue', ($yu, $eh)),
  ('uai', ($u, $ai)),
  ('ui', ($u, $ei)),
  ('uei', ($u, $ei)),
  ('uan', ($u, $an)),
  ('un', ($u, $en)),
  ('uang', ($u, $ang)),
  ('ong', ($u, $eng)),
  ('v', ($yu, 0)),
  ('ve', ($yu, $eh)),
  ('van', ($yu, $an)),
  ('vn', ($yu, $en)),
  ('iong', ($yu, $eng)),
  ('ü', ($yu, 0)),
  ('üe', ($yu, $eh)),
  ('ue', ($yu, $eh)),
  ('üan', ($yu, $an)),
  ('ün', ($yu, $en)),
];

const medRimeToAscii = {
  (0, $a): 'a',
  (0, $o): 'o',
  (0, $e): 'e',
  (0, $eh): 'eh', //yeh is bad
  (0, $ai): 'ai',
  (0, $ei): 'ei',
  (0, $ao): 'ao',
  (0, $ou): 'ou',
  (0, $an): 'an',
  (0, $en): 'en',
  (0, $ang): 'ang',
  (0, $eng): 'eng',
  (0, $er): 'er',
  (0, 0): 'i', //(r)i
  ($i, 0): 'i',
  ($i, $a): 'ia',
  ($i, $o): 'io',
  ($i, $eh): 'ie',
  ($i, $ai): 'iai',
  ($i, $ao): 'iao',
  ($i, $ou): 'iu',
  ($i, $an): 'ian',
  ($i, $en): 'in',
  ($i, $ang): 'iang',
  ($i, $eng): 'ing',
  ($u, 0): 'u',
  ($u, $a): 'ua',
  ($u, $eh): 'ue',
  ($u, $o): 'uo',
  ($u, $ai): 'uai',
  ($u, $ei): 'ui',
  ($u, $an): 'uan',
  ($u, $en): 'un',
  ($u, $ang): 'uang',
  ($u, $eng): 'ong',
  ($yu, 0): 'v',
  ($yu, $eh): 've',
  ($yu, $an): 'van',
  ($yu, $en): 'vn',
  ($yu, $eng): 'iong',
};
